version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmb_websocket_swoole
    restart: always
    depends_on:
      - db
    ports:
      - "${APP_PORT:-9501}:${APP_PORT:-9501}"
    volumes:
      - .:/usr/src/app
    networks:
      - cmb_websocket_backend
    entrypoint: ["./bin/start_server_development.sh"]

  db:
    image: mysql:latest
    container_name: cmb_websocket_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    volumes:
      - cmb_websocket_database:/var/lib/mysql
    networks:
      - cmb_websocket_backend

networks:
  cmb_websocket_backend:
    driver: bridge

volumes:
  cmb_websocket_database: